In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
import os
os.environ["CUDA_VISIBLE_DEVICES"]= '1'
gpus = tf.config.experimental.list_physical_devices(device_type='GPU')
for gpu in gpus:
    tf.config.experimental.set_memory_growth(gpu, True)

/Users/lai/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/lai/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/lai/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/lai/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:5

In [50]:
dataset = pd.read_csv('/Users/lai/Downloads/Final_Dataset_NN.csv')

In [51]:
dataset = dataset.drop(['Unnamed: 0'],axis = 1)

In [91]:
dataset.columns[-70:]

Index(['傳產-塑膠', '傳產-生技', '傳產-航運', '金融-金控', '電子上游-IC-設計', '電子上游-LED及光元件',
       '電子下游-電信服務', '傳產-其他', '傳產-汽車', '傳產-自行車', '傳產-鋼鐵', '傳產-電機', '傳產-食品',
       '電子上游-DRAM銷售', '電子上游-IC-封測', '電子上游-PCB-製造', '電子上游-被動元件', '電子上游-連接元件',
       '電子中游-主機板', '傳產-化學工業', '電子上游-IC-其他', '電子下游-筆記型電腦', '傳產-紡織纖維', '傳產-電線電纜',
       '電子上游-IC-代工', '電子上游-IC-製造', '電子下游-光碟片', '電子中游-LCD-TFT面板',
       '電子中游-NB與手機零組件', '電子上游-PCB-材料設備', '電子下游-太陽能', '電子中游-LCD-零組件',
       '電子中游-儀器設備工程', '電子中游-其他', '電子中游-網通', '傳產-百貨', '電子中游-LCD-STN面板',
       '電子中游-EMS', '傳產-營建', '軟體-遊戲', '電子中游-機殼', '電子下游-工業電腦', '金融-銀行',
       '電子中游-通訊設備', '電子中游-電源供應器', '電子中游-變壓器與UPS', '傳產-橡膠', '軟體-其他',
       '電子中游-光學鏡片', '傳產-汽車零組件', '電子上游-IC-通路', '電子下游-其他', '電子下游-手機製造', '傳產-水泥',
       '傳產-紙業', '電子中游-PC介面卡', '電子下游-安全監控', '金融-證券', '電子上游-IC-DRAM製造',
       '電子下游-商業自動化', '電子下游-資訊通路', '傳產-觀光', '金融-保險', '軟體-系統整合', '電子下游-消費電子',
       '傳產-玻璃陶瓷', '傳產-高爾夫球', '電子下游-顯示器', '電子下游-掃描器', '電子下游-數位相機'],
      dtype='object')

In [59]:
x = dataset.iloc[:,1:4116].values

In [60]:
y = dataset.iloc[:,4116:].values

In [82]:
y[0].shape

(70,)

In [62]:
y.shape

(2023, 70)

In [63]:
x.shape

(2023, 4115)

In [64]:
from sklearn.model_selection import train_test_split

In [65]:
x_train,x_val,y_train,y_val = train_test_split(x,y,test_size = 0.1,random_state = 1)

In [146]:
model = keras.models.Sequential()
model.add(keras.layers.Dense(2000, activation="tanh",input_shape = (4115,)))
model.add(keras.layers.Dense(1000, activation="tanh"))
model.add(keras.layers.Dense(500, activation="tanh"))
model.add(keras.layers.Dense(250, activation="tanh"))
model.add(keras.layers.Dense(100, activation="tanh"))
model.add(keras.layers.Dense(70, activation="sigmoid"))

In [147]:
model.compile(loss="binary_crossentropy",
              optimizer="sgd",
              metrics=["accuracy"])

In [148]:
logdir = 'NN_Fintech_MultiLabel'
callbacks = keras.callbacks.TensorBoard(log_dir = logdir)

In [149]:
history = model.fit(x_train, y_train, epochs=10,
                    validation_data=(x_val, y_val),callbacks = [callbacks])

Train on 1820 samples, validate on 203 samples
Epoch 1/10
1820/1820 [==============================] - 2s 1ms/sample - loss: 0.6711 - acc: 0.5853 - val_loss: 0.6225 - val_acc: 0.6634
Epoch 2/10
1820/1820 [==============================] - 2s 1ms/sample - loss: 0.5886 - acc: 0.7059 - val_loss: 0.5604 - val_acc: 0.7453
Epoch 3/10
1820/1820 [==============================] - 2s 1ms/sample - loss: 0.5323 - acc: 0.7758 - val_loss: 0.5105 - val_acc: 0.8017
Epoch 4/10
1820/1820 [==============================] - 2s 1ms/sample - loss: 0.4852 - acc: 0.8278 - val_loss: 0.4674 - val_acc: 0.8465
Epoch 5/10
1820/1820 [==============================] - 2s 1ms/sample - loss: 0.4443 - acc: 0.8684 - val_loss: 0.4301 - val_acc: 0.8817
Epoch 6/10
1820/1820 [==============================] - 2s 1ms/sample - loss: 0.4089 - acc: 0.8973 - val_loss: 0.3979 - val_acc: 0.9035
Epoch 7/10
1820/1820 [==============================] - 2s 1ms/sample - loss: 0.3785 - acc: 0.9151 - val_loss: 0.3705 - val_acc: 0.9171
E

In [164]:
from tensorflow.keras.models import load_model

In [165]:
model = load_model('test.h5')

In [134]:
x_val.shape

(203, 4115)

In [138]:
x_val[0].shape

(4115,)

In [139]:
y_val[0].shape

(70,)

In [167]:
x_val[0]

array([ 0.,  6., 51., ...,  0.,  0.,  0.])

In [170]:
x_val.ndim

2

In [173]:
x_val[0].ndim

1

In [166]:
model.predict([[x_val[0]]])

array([[0.02465346, 0.04964346, 0.11302286, 0.58922386, 0.01545924,
        0.01659977, 0.02000117, 0.0483641 , 0.0093132 , 0.00379103,
        0.03967524, 0.01641163, 0.02859694, 0.00520852, 0.01870412,
        0.03703421, 0.02409256, 0.01233795, 0.00924319, 0.00771454,
        0.00612101, 0.03273767, 0.03158951, 0.00382277, 0.39771822,
        0.01694408, 0.00678369, 0.05530298, 0.01995564, 0.01054007,
        0.01073173, 0.00712371, 0.00533435, 0.01132938, 0.01871258,
        0.01334485, 0.0057855 , 0.05584937, 0.01347339, 0.0108901 ,
        0.00531265, 0.00541067, 0.06656238, 0.01218084, 0.01210958,
        0.00309843, 0.0186618 , 0.00720084, 0.00633541, 0.01214328,
        0.01092109, 0.00876972, 0.00970814, 0.01064909, 0.01571867,
        0.00629273, 0.00297776, 0.0079982 , 0.00898409, 0.00333351,
        0.00543761, 0.01899385, 0.02030116, 0.01033938, 0.00619679,
        0.00225629, 0.00480402, 0.00300215, 0.0075027 , 0.00308113]],
      dtype=float32)

In [137]:
y_pred = model.predict(x_val)

(203, 70)

In [174]:
# model.predict(x_val[0])

In [79]:
y_val[12]

array([0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0])

In [98]:
dataset.iloc[:, -70:]

傳產-塑膠  傳產-生技  傳產-航運  金融-金控  電子上游-IC-設計  電子上游-LED及光元件  電子下游-電信服務  傳產-其他  \
0         1      1      1      1           1             1          1      0   
1         0      1      1      0           0             1          0      1   
2         1      0      0      0           0             0          0      0   
3         0      1      0      0           1             1          0      0   
4         1      1      0      0           1             0          0      0   
...     ...    ...    ...    ...         ...           ...        ...    ...   
2018      0      0      0      0           0             0          0      0   
2019      0      0      0      0           0             0          0      0   
2020      0      0      0      0           0             0          0      0   
2021      1      0      0      0           0             0          0      0   
2022      0      0      0      0           0             0          0      0   

      傳產-汽車  傳產-自行車  ...  電子下游-資訊通路  傳產-觀光  金融-保險  軟體-系統整合  電子下游-消費電子  \
0         0       0  ...          0      0      0        0          0   
1         1       1  ...          0      0      0        0          0   
2         0       0  ...          0      0      0        0          0   
3         0       0  ...          0      0      0        0          0   
4         0       0  ...          0      0      0        0          0   
...     ...     ...  ...        ...    ...    ...      ...        ...   
2018      0       0  ...          0      0      0        0          0   
2019      0       0  ...          0      0      0        0          0   
2020      0       0  ...          0      0      0        0          0   
2021      0       0  ...          0      0      0        0          0   
2022      0       0  ...          0      0      0        0          0   

      傳產-玻璃陶瓷  傳產-高爾夫球  電子下游-顯示器  電子下游-掃描器  電子下游-數位相機  
0           0        0         0         0          0  
1           0        0         0         0          0  
2           0        0         0         0          0  
3           0        0         0         0          0  
4           0        0         0         0          0  
...       ...      ...       ...       ...        ...  
2018        0        0         0         0          0  
2019        0        0         0         0          0  
2020        0        0         0         0          0  
2021        0        0         0         0          0  
2022        0        0         0         0          0  

[2023 rows x 70 columns]

In [101]:
type(dataset)

pandas.core.frame.DataFrame

In [100]:
type(y_pred)

numpy.ndarray

In [96]:
dataset.columns[-70:]

Index(['傳產-塑膠', '傳產-生技', '傳產-航運', '金融-金控', '電子上游-IC-設計', '電子上游-LED及光元件',
       '電子下游-電信服務', '傳產-其他', '傳產-汽車', '傳產-自行車', '傳產-鋼鐵', '傳產-電機', '傳產-食品',
       '電子上游-DRAM銷售', '電子上游-IC-封測', '電子上游-PCB-製造', '電子上游-被動元件', '電子上游-連接元件',
       '電子中游-主機板', '傳產-化學工業', '電子上游-IC-其他', '電子下游-筆記型電腦', '傳產-紡織纖維', '傳產-電線電纜',
       '電子上游-IC-代工', '電子上游-IC-製造', '電子下游-光碟片', '電子中游-LCD-TFT面板',
       '電子中游-NB與手機零組件', '電子上游-PCB-材料設備', '電子下游-太陽能', '電子中游-LCD-零組件',
       '電子中游-儀器設備工程', '電子中游-其他', '電子中游-網通', '傳產-百貨', '電子中游-LCD-STN面板',
       '電子中游-EMS', '傳產-營建', '軟體-遊戲', '電子中游-機殼', '電子下游-工業電腦', '金融-銀行',
       '電子中游-通訊設備', '電子中游-電源供應器', '電子中游-變壓器與UPS', '傳產-橡膠', '軟體-其他',
       '電子中游-光學鏡片', '傳產-汽車零組件', '電子上游-IC-通路', '電子下游-其他', '電子下游-手機製造', '傳產-水泥',
       '傳產-紙業', '電子中游-PC介面卡', '電子下游-安全監控', '金融-證券', '電子上游-IC-DRAM製造',
       '電子下游-商業自動化', '電子下游-資訊通路', '傳產-觀光', '金融-保險', '軟體-系統整合', '電子下游-消費電子',
       '傳產-玻璃陶瓷', '傳產-高爾夫球', '電子下游-顯示器', '電子下游-掃描器', '電子下游-數位相機'],
      dtype='object')

In [95]:
y_pred[12]

array([0.06627071, 0.31492478, 0.1009506 , 0.28605363, 0.29223955,
       0.2382138 , 0.398913  , 0.5526782 , 0.10901561, 0.11329958,
       0.15077686, 0.2665918 , 0.22155708, 0.15649295, 0.25412002,
       0.36315635, 0.26840585, 0.1492151 , 0.31593338, 0.22827211,
       0.13782099, 0.24397093, 0.11202398, 0.13180038, 0.283452  ,
       0.23885834, 0.06396109, 0.0711773 , 0.15948024, 0.14807785,
       0.21541727, 0.1784544 , 0.11815122, 0.10294643, 0.23900989,
       0.17618072, 0.18201175, 0.2881381 , 0.39759177, 0.05228624,
       0.07286063, 0.1740166 , 0.06894338, 0.13008681, 0.23385102,
       0.17714348, 0.09308735, 0.0966225 , 0.16560712, 0.12447995,
       0.21891195, 0.19688198, 0.24109069, 0.32964718, 0.0797559 ,
       0.0636538 , 0.1414496 , 0.07287389, 0.1289739 , 0.11093813,
       0.24101591, 0.10947922, 0.12194067, 0.11989409, 0.09719321,
       0.10579962, 0.07369754, 0.05612499, 0.07535496, 0.07822755],
      dtype=float32)

In [94]:
sorted(y_pred[12], reverse=True)[:5]

[0.5526782, 0.398913, 0.39759177, 0.36315635, 0.32964718]

In [108]:
array = np.concatenate(y_pred[12], axis=None)

In [112]:
df = pd.DataFrame(dataset.columns[-70:])

In [119]:
merge = pd.DataFrame(pd.np.column_stack([df, y_pred[12]]))

In [123]:
merge

0          1
0        傳產-塑膠  0.0662707
1        傳產-生技   0.314925
2        傳產-航運   0.100951
3        金融-金控   0.286054
4   電子上游-IC-設計    0.29224
..         ...        ...
65     傳產-玻璃陶瓷     0.1058
66     傳產-高爾夫球  0.0736975
67    電子下游-顯示器   0.056125
68    電子下游-掃描器   0.075355
69   電子下游-數位相機  0.0782275

[70 rows x 2 columns]

In [130]:
s = merge.sort_index()

In [133]:
s.sort_values(1, ascending=False)[:5]

0         1
7         傳產-其他  0.552678
6     電子下游-電信服務  0.398913
38        傳產-營建  0.397592
15  電子上游-PCB-製造  0.363156
53        傳產-水泥  0.329647

In [20]:
ind = np.argpartition(y_pred[9], -11)[-11:]

IndexError: index 9 is out of bounds for axis 0 with size 3

In [42]:
ind

array([56, 50, 39, 32, 27, 58, 38, 15, 10,  3, 61])

In [43]:
y_pred[9][ind]

array([0.12348142, 0.12445366, 0.19302976, 0.17833504, 0.22872153,
       0.22575212, 0.25911522, 0.14135143, 0.1744698 , 0.1280914 ,
       0.14316043], dtype=float32)